services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && NODE_ENV=production yarn build
    startCommand: rsync -a public/ /data/public/ && NODE_ENV=staging yarn start
    healthCheckPath: /_health
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: staging
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE
        value: fr